import { artifactInventory, highlightEvents, msBetween, timestamp, topEventTypes, valueShape } from "./runEvidence.js";
import { runOutcomeSummary } from "./runOutcomePresentation.js";

export const RUN_RETROSPECTIVE_ARTIFACT_NAME = "run-retrospective.json";
export const RUN_RETROSPECTIVE_SCHEMA_VERSION = "smithers.hub.run-retrospective.v1";

const GENERATED_RUN_ARTIFACT_NAMES = [RUN_RETROSPECTIVE_ARTIFACT_NAME, "run-obstruction-analysis.json"];

function diagnosticSummary(diagnostics) {
  if (!diagnostics) return null;
  return {
    status: diagnostics.status || "",
    headline: diagnostics.headline || "",
    reason: diagnostics.reason || "",
    failedStep: diagnostics.failedStep || "",
    failureType: diagnostics.failureType || "",
    failedAt: diagnostics.failedAt || "",
    cancelledBy: diagnostics.cancelledBy || "",
    approval: diagnostics.approval || null,
    diagnosticArtifacts: (diagnostics.artifacts || []).map((artifact) => ({
      id: artifact.id || "",
      name: artifact.name || "",
      mimeType: artifact.mimeType || "",
      deepLink: artifact.deepLink || ""
    }))
  };
}

export function buildRunRetrospectiveArtifact({
  run,
  capability = null,
  artifacts = [],
  logSummary = {},
  diagnostics = null,
  generatedAt = timestamp()
} = {}) {
  const inventory = artifactInventory(artifacts, { generatedNames: GENERATED_RUN_ARTIFACT_NAMES });
  // Prefer the decorated summary that `withRunLinks` already computed; recompute
  // from raw output if the caller passed a bare run so this survives direct-use
  // paths too (tests, reap-stuck runs before decoration).
  const outcomeSummary = run?.outcomeSummary && typeof run.outcomeSummary === "object" && !Array.isArray(run.outcomeSummary)
    ? run.outcomeSummary
    : runOutcomeSummary(run);
  const changedFiles = Array.isArray(outcomeSummary.files) ? outcomeSummary.files : [];
  const changedFileCount = Number.isFinite(outcomeSummary.changedFiles) ? outcomeSummary.changedFiles : changedFiles.length;
  const churn = outcomeSummary.churn && typeof outcomeSummary.churn === "object" && !Array.isArray(outcomeSummary.churn)
    ? { additions: Number(outcomeSummary.churn.additions) || 0, deletions: Number(outcomeSummary.churn.deletions) || 0 }
    : null;
  const digest = typeof outcomeSummary.digest === "string" ? outcomeSummary.digest : "";
  const content = {
    schemaVersion: RUN_RETROSPECTIVE_SCHEMA_VERSION,
    generatedAt,
    generatedBy: "runyard",
    purpose: "Lightweight run evidence for later batch knowledge analysis.",
    policy: {
      artifactOnly: true,
      autoMutations: false,
      mutatedSoftAssets: []
    },
    run: {
      id: run?.id || "",
      status: run?.status || "",
      title: run?.title || "",
      description: run?.description || "",
      capabilitySlug: run?.capabilitySlug || "",
      capabilityName: run?.capabilityName || "",
      workflowVersion: run?.workflowVersion ?? null,
      runnerId: run?.runnerId || "",
      currentStep: run?.currentStep || "",
      createdAt: run?.createdAt || "",
      assignedAt: run?.assignedAt || "",
      startedAt: run?.startedAt || "",
      completedAt: run?.completedAt || "",
      durationMs: run?.durationMs ?? msBetween(run?.startedAt || run?.createdAt, run?.completedAt),
      deepLink: run?.deepLink || ""
    },
    workflow: capability
      ? {
          slug: capability.slug || run?.capabilitySlug || "",
          name: capability.name || run?.capabilityName || "",
          version: capability.version ?? run?.workflowVersion ?? null,
          engine: capability.workflow?.engine || "",
          entry: capability.workflow?.entry || capability.workflow?.file || "",
          requiredRunnerTags: capability.requiredRunnerTags || [],
          requiredSkills: capability.requiredSkills || [],
          requiredAgents: capability.requiredAgents || [],
          deepLink: capability.deepLink || ""
        }
      : null,
    timing: {
      queuedMs: msBetween(run?.createdAt, run?.assignedAt || run?.startedAt),
      executionMs: msBetween(run?.startedAt, run?.completedAt),
      totalMs: msBetween(run?.createdAt, run?.completedAt)
    },
    outcome: {
      status: run?.status || "",
      succeeded: run?.status === "succeeded",
      changedFileCount,
      changedFiles,
      churn,
      digest,
      workProduct: outcomeSummary.workProduct || "",
      diagnostics: diagnosticSummary(diagnostics)
    },
    evidence: {
      eventTotals: logSummary.totals || { events: 0, highlights: 0, errors: 0, warnings: 0 },
      eventCategories: logSummary.categories || [],
      eventSeverities: logSummary.severities || [],
      topEventTypes: topEventTypes(logSummary),
      highlightEvents: highlightEvents(logSummary),
      artifactInventory: inventory,
      outputShape: valueShape(run?.output)
    },
    notes: [
      "This artifact is generated by the Hub at run terminalization.",
      "It does not include full raw input objects, raw artifact contents, or raw output values.",
      "It did not modify workflows, skills, agents, knowledge, prompts, or other soft assets."
    ]
  };

  return {
    name: RUN_RETROSPECTIVE_ARTIFACT_NAME,
    mimeType: "application/json",
    content: JSON.stringify(content, null, 2),
    metadata: {
      generatedBy: "runyard",
      kind: "run-retrospective",
      schemaVersion: RUN_RETROSPECTIVE_SCHEMA_VERSION
    }
  };
}
